# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1bca6ec9eee5840988e6c6c406889e2250cb935af7822c507fc34f11b787f92383e871c511baadab398c70086c8756a35af981bda787019b61dd3ec0f773c11

test:
  secret_key_base: 7188d61500e8e1a1bd03be4b7ddb9ceebb1015571e290c4a9cd60fef730863359ee4ef1d84d6a2e961ad512ab868c7a6b7b83efe6230e4cdc3b574222ae72d04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
